name: Store state file in s3

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Initialize Terraform
      run: terraform init
      continue-on-error: false
    - name: Validate Terraform
      run: terraform validate
    - name: Plan terraform
      run: terraform plan
    - name: Apply Terraform changes
      run: terraform apply -auto-approve
    # - name: push state file to s3